### ISSUE TITLE
subcollection

### ISSUE THREAD

**Issue by hooloom** [dalenguyen/serverless-rest-api#2]
trying to get the sub collection as described in the readme.   not having any luck.

would like to return the subs collection and its documents the same.  First is the latest attempt to get this to work.  Second is what does work but never gets the sub collection.  ****PLEASE HELP

`app.get('/', (req, res) => {
    firebaseHelper.firestore
    .backup(db, syndicatedCollection, cityCollection)
    .then(data => console.log(JSON.stringify(data)));
})

app.get('/syndicated/:orgType/city/:cityName', (req, res) => {
    firebaseHelper.firestore
        .getDocument(db, syndicatedCollection, req.params.cityName)
        .then(doc => res.status(200).send(doc));
})`

**Comment by hooloom** [comment]
TypeError: Object.entries is not a function     at FirestoreHelper.<anonymous> (/user_code/node_modules/firebase-functions-helper/dist/firestore.js:208:45)     at next (native)     at /user_code/node_modules/firebase-functions-helper/dist/firestore.js:7:71     at __awaiter (/user_code/node_modules/firebase-functions-helper/dist/firestore.js:3:12)     at FirestoreHelper.getSubCollection (/user_code/node_modules/firebase-functions-helper/dist/firestore.js:207:16)     at results.then.dt (/user_code/node_modules/firebase-functions-helper/dist/firestore.js:184:26)     at process._tickDomainCallback (internal/process/next_tick.js:135:7) |  
-- | --

**Comment by hooloom** [comment]
> TypeError: Object.entries is not a function at FirestoreHelper. (/user_code/node_modules/firebase-functions-helper/dist/firestore.js:208:45) at next (native) at /user_code/node_modules/firebase-functions-helper/dist/firestore.js:7:71 at __awaiter (/user_code/node_modules/firebase-functions-helper/dist/firestore.js:3:12) at FirestoreHelper.getSubCollection (/user_code/node_modules/firebase-functions-helper/dist/firestore.js:207:16) at results.then.dt (/user_code/node_modules/firebase-functions-helper/dist/firestore.js:184:26) at process._tickDomainCallback (internal/process/next_tick.js:135:7)

fixed this by adding ,
  "engines": {"node": "8"} to package.json

**Comment by dalenguyen** [comment]
Yes, it requires a newer version of Node.
