### ISSUE TITLE
Function request returns google auth page

### ISSUE THREAD

**Issue by CJX3M** [dalenguyen/serverless-rest-api#6]
When trying to request the deployed function, I'm meet with a Google Authentification page
![image](https://user-images.githubusercontent.com/5133204/71493463-2f7a2f80-27fc-11ea-854c-c52311c3a21a.png)

Rather than cloning the repo, I wrote the code following the blogs post. Already turned authentification of the project to Anonymous

**Comment by dalenguyen** [comment]
Hi @CJX3M, can you test it on your local machine? 

```
firebase serve
```

If it asks for Google Credentials, you can check export GOOGLE_APPLICATION_CREDENTIALS through the terminal before running the script.

**Comment by CJX3M** [comment]
Well, just tried to do it, no credentials where requested, but also, when querying the service, a 404 was returned

![image](https://user-images.githubusercontent.com/5133204/71602938-bf2f1f00-2b17-11ea-95b5-721580af4a8d.png)

![image](https://user-images.githubusercontent.com/5133204/71602945-ceae6800-2b17-11ea-8d74-356e6a57b1aa.png)

**Comment by dalenguyen** [comment]
@CJX3M, the express app has a path. Check your path in the app. And make sure that you are doing POST request in the app too. For example in your case:

```
app.post('/messages', async (req, res) => {
   // do something
})
```

**Comment by CJX3M** [comment]
This is my index.ts file

```
import * as functions from 'firebase-functions';
import * as admin from 'firebase-admin';
import * as firebaseHelper from 'firebase-functions-helper/dist';
import * as express from 'express';
import * as bodyParser from "body-parser";

admin.initializeApp(functions.config().firebase);
const db = admin.firestore();

const app = express();
const main = express();

main.use(bodyParser.json());
main.use(bodyParser.urlencoded({ extended: false }));
main.use('/api/v1', app);

const messageCol = 'messages';

export const webApi = functions.https.onRequest(main);

interface Message {
    text: String
}

// Add new contact
app.post('/messages', async (req, res) => {
    try {
        const message: Message = {
            text: req.body.text
        }

        const newDoc = await firebaseHelper.firestore
            .createNewDocument(db, messageCol, message);
        res.status(201).send(`Created a new messages: ${newDoc.id}`);
    } catch (error) {
        res.status(400).send(`messages should only contains text!!!`)
    }        
})

// Update new contact
app.patch('/messages/:msgId', async (req, res) => {
    const updatedDoc = await firebaseHelper.firestore
        .updateDocument(db, messageCol, req.params.msgId, req.body);
    res.status(204).send(`Update a new messages: ${updatedDoc}`);
})

// View a contact
app.get('/messages/:msgId', (req, res) => {
    firebaseHelper.firestore
        .getDocument(db, messageCol, req.params.msgId)
        .then(doc => res.status(200).send(doc))
        .catch(error => res.status(400).send(`Cannot get messages: ${error}`));
})

// View all contacts
app.get('/messages', (req, res) => {
    firebaseHelper.firestore
        .backup(db, messageCol)
        .then(data => res.status(200).send(data))
        .catch(error => res.status(400).send(`Cannot get messages: ${error}`));
})

// Delete a contact 
app.delete('/messages/:msgId', async (req, res) => {
    const deletedMessage = await firebaseHelper.firestore
        .deleteDocument(db, messageCol, req.params.msgId);
    res.status(204).send(`message is deleted: ${deletedMessage}`);
})

export { app };
```

I also can't see why my endpoints are not being reached. I have quite a few years of experience in express, and this is the first time I see no problem with my paths and can't reach them. Still, I got more confussed to the fact that a call to a deployed endpoint returns a googl auth page

**Comment by dalenguyen** [comment]
Did you build the functions before running it?

**Comment by CJX3M** [comment]
Well, I run `"serve": "npm run build && firebase serve --only functions"` script to test, so yeah, I believe I build the functions before running the local server

**Comment by dalenguyen** [comment]
I got it. 

This line: 

```
main.use('/api/v1', app);
```
The path you request doesn't exist. 

Try this your-path: /webApi/api/v1/messages

**Comment by CJX3M** [comment]
Well, that supposed to have done the trick. I don't see anything in the storage, but I can debug that later.

Meanwhile, the request returned a 200 and no Googl auth page

![image](https://user-images.githubusercontent.com/5133204/71649749-6950a780-2cce-11ea-924e-7197977209e5.png)

**Comment by dalenguyen** [comment]
I'm glad that it worked.
